language: python

sudo: false

env:
  global:
  - LILYPOND_URL="http://lilypond.org/downloads/binaries/linux-64/"
  - LILYPOND_VERSION=2.19.65

python:
- 3.6

addons:
  apt:
    packages:
    - freepats
    - ghostscript
    - graphviz
    - imagemagick
    - timidity

before_install:
- wget -q ${LILYPOND_URL}lilypond-${LILYPOND_VERSION}-1.linux-64.sh
- sh lilypond-$LILYPOND_VERSION-1.linux-64.sh --batch
- export PATH=/home/travis/bin:$PATH
- pip install -U pip coverage
- pip install -U https://github.com/Abjad/abjad/archive/master.zip
- pip install -U https://github.com/josiah-wolf-oberholtzer/uqbar/archive/master.zip
- pip install --no-deps --target /tmp/typehints https://github.com/Abjad/abjad/archive/master.zip
- pip install --no-deps --target /tmp/typehints https://github.com/josiah-wolf-oberholtzer/uqbar/archive/master.zip
- export MYPYPATH=/tmp/typehints

install:
- pip install -e .[development]

script:
- pytest
- jupyter nbconvert --to=html --ExecutePreprocessor.enabled=True test/test.ipynb
- mypy abjadext
