language: python

sudo: false

env:
  global:
  - LILYPOND_URL="http://lilypond.org/downloads/binaries/linux-64/"
  - LILYPOND_VERSION=2.19.65

python:
- 3.6

addons:
  apt:
    packages:
    - freepats
    - ghostscript
    - graphviz
    - imagemagick
    - timidity

before_install:
- wget -q ${LILYPOND_URL}lilypond-${LILYPOND_VERSION}-1.linux-64.sh
- sh lilypond-$LILYPOND_VERSION-1.linux-64.sh --batch
- export PATH=/home/travis/bin:$PATH
- pip install -U pip
- pip install https://github.com/Abjad/abjad/archive/master.zip
- pip install pytest coverage

install:
- pip install -e .

script:
- py.test
- jupyter nbconvert --to=html --ExecutePreprocessor.enabled=True test/test.ipynb
